### ISSUE TITLE
Some question about XilinxS7Phy

### ISSUE THREAD

**Issue by LurenAA** [SpinalHDL/SpinalHDL#1219]
1. What do the parameters "clk90" "serdesClk0" and "serdesClk90" mean in XilinxS7Phy?
2. Can I use “XilinxS7Phy” in the same way as file "SdramXdrDdr3S7Cocotb.scala", but with one question: In line 20 of the code in "SdramXdrDdr3S7Cocotb.scala", there is a function "Clock.sync(clk0, clk90)," but I couldn't find any documentation or other instances of this function being used elsewhere. What does this function do?

Thank you.

**Comment by andreasWallner** [comment]
> 1. What do the parameters "clk90" "serdesClk0" and "serdesClk90" mean in XilinxS7Phy?

The parameters that you mention are for passing the clocks that the component needs (90 degree phase shifted version of system clock + "normal" and 90 degree shifted version of clock for the SERDES blocks. These need to be passed to the component since you need to generate them dependent on you FPGA/Board/Design in a PLL or MMCM.

>     2. Can I use “XilinxS7Phy” in the same way as file "SdramXdrDdr3S7Cocotb.scala", but with one question: In line 20 of the code in "SdramXdrDdr3S7Cocotb.scala", there is a function "Clock.sync(clk0, clk90)," but I couldn't find any documentation or other instances of this function being used elsewhere. What does this function do?

It adds tags that those CDs are synchronous see `core/ClockDomain.scala`

Note: that code was commented out in 2019, if you look for a reference look for the SpinalSim version of the test (`/tester/src/test/scala/spinal/lib/memory/sdram/xdr/SdramXdrSdrSpinalSim.scala`)
