### ISSUE TITLE
the CI failed while "install cached tools" with error that ghdl is missing.

### ISSUE THREAD

**Issue by Readon** [SpinalHDL/SpinalHDL#639]
I have tracked the log, find that GNAT installation failed while preparing ghdl. Here is the log.
<img width="919" alt="1646919291(1)" src="https://user-images.githubusercontent.com/3614708/157673120-b968883d-ea32-494a-ab1a-96c6a3209552.png">

**Comment by Readon** [comment]
I tried to update the version number of tools which force recache the repos. 
It still report this problem even with [fix].(https://github.com/SpinalHDL/SpinalHDL/commit/4b19e7b2bb1984776713656ebbe02a405d52e33d)

**Comment by Dolu1990** [comment]
Hmm i think this is another issue : 
/home/runner/.local/lib/python3.8/site-packages/cocotb/share/makefiles/simulators/Makefile.ghdl:51: *** "Unable to locate command >ghdl<".  Stop.

Because of 
2022-03-11T01:38:47.7417980Z Cloning into 'ghdl-build'...
2022-03-11T01:38:55.0281354Z HEAD is now at 2fb2384d Prepare release 1.0.0
2022-03-11T01:38:55.0516082Z Sorry, you need GNAT to build GHDL.  See the README

So seems we need to install packages before isntalling GHDL

**Comment by Dolu1990** [comment]
Pushed a fix

**Comment by Readon** [comment]
the cause of this error is missing of gnat.


 
---Original---
From: ***@***.***&gt;
Date: 2022/3/11 20:28:35
To: ***@***.***&gt;;
Cc: "State ***@***.******@***.***&gt;;
Subject: Re: [SpinalHDL/SpinalHDL] the CI failed while "install cached tools"with error that ghdl is missing. (Issue #639)




 
Hmm i think this is another issue :
 /home/runner/.local/lib/python3.8/site-packages/cocotb/share/makefiles/simulators/Makefile.ghdl:51: *** "Unable to locate command &gt;ghdl<".  Stop.
 
Because of
 2022-03-11T01:38:47.7417980Z Cloning into 'ghdl-build'...
 2022-03-11T01:38:55.0281354Z HEAD is now at 2fb2384d Prepare release 1.0.0
 2022-03-11T01:38:55.0516082Z Sorry, you need GNAT to build GHDL.  See the README
 
So seems we need to install packages before isntalling GHDL
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
