### ISSUE TITLE
The Mem write enable function

### ISSUE THREAD

**Issue by liqx-github** [SpinalHDL/SpinalHDL#674]
![QQ图片20220403164738](https://user-images.githubusercontent.com/84823360/161419772-ff009ed7-78cc-4f0c-b2b9-a198a5b2cf07.png)

Hello! I'm having problems using Mem's write Enable function. As shown in the picture, The condition pickMem === U(i) will not work when I place io.memWr in the enable parameter of Mem, What kind of consideration is that?

**Comment by Dolu1990** [comment]
Hi,

So the Mem API is made in a way where, either you don't specify the function enable argument, and you let the conditional scope do all the work, either you specify the function enable argeuement, and it will be the only thing considered.

So it is the expected behaviour, then maybe it isn't the best one.

Does it make sense ?

**Comment by liqx-github** [comment]
I got it. Thank you very much!
