### ISSUE TITLE
Possibly add HDL comment to back trace Scala code line:column?

### ISSUE THREAD

**Issue by kellenwang1017** [SpinalHDL/SpinalHDL#783]
Hi, We noticed that in Chisel it is possible to switch on appendix comment in HDL with annotations of corresponding origional Scala line:column information, syntax like this:

if(a) begin // @[Foo.scala 110:2]
  b <= 1'b1 // @[Foo.scala 111:4]
end

would it be possible to add similar features in SpinalHDL? We think it may help with bug back tracing in practice.

**Comment by Dolu1990** [comment]
So about // @[Foo.scala 111:4]

Basicaly, it can be usefull, but it break down realy fast
as soon things are encapsulated into functions which can be called from multiple place it isn't so usefull
For instance :
myStream.stage()

All the things created into the stage function will be Stream.scala xxx.y which isn't very usefull, you would need kind of the full stack trace XD

that's why in some ways, SpinalHDL focus more on name propagation

Overall, it could be implemented without much paine, there is already somthing kind of similar (see loc : https://github.com/SpinalHDL/SpinalHDL/blob/dev/core/src/main/scala/spinal/core/when.scala#L78) , but it isn't a silver bullet as far as i can see.
